### PR TITLE
Glutin 0.17 upgrade merge master @ f3a76e2

### PR DESCRIPTION
**Pull request by adrienthebo**
This is a quick and dirty merge-up of master at f3a76e2 into the `glutin-0.17-upgrade` branch. I'm new to Alacritty so my conflict resolutions may be a bit naive, but the resulting code has been stable thus far and all tests pass.

### CODE REVIEW

**Comment by adrienthebo** [comment]
Also, I suspect that I had an autofixer running rustfmt on file saves, which may have resulted in unnecessarily large diffs. If this branch is useful to you but the reformatting is a problematic, give me a shout and I'll re-run the merge up.

**Comment by chrisduerr** [comment]
Running rustfmt on Alacritty is currently not admissible, since it makes the code pretty much impossible to review.

If you're willing to go through the process again without running rustfmt on the code, I'd appreciate it.

**Comment by adrienthebo** [comment]
@chrisduerr agreed, sorry about that - reformatting code when resolving merge conflicts is pretty ghastly. I've re-run the merge without the reformatting. Could you give this another look?

**Review by chrisduerr — APPROVED** [review]
Looks good, thanks for going through the trouble or merging master back into this!

@mkeeler I'd recommend a squash and merge, no need to add all the commits.

**Pull request merged**
